version: "2.4"

services:
  redis:
    image: "redis:alpine"

  queue:
    image: rabbitmq:3-management-alpine
    restart: on-failure

  api:
    build: ..
    ports:
      - 8080:8080
    environment:
      - REDIS_URL
      - RABBIT_URL
    depends_on:
      - redis
      - queue
    command: 'uvicorn capts.app.main:app --host 0.0.0.0 --port 8080'

  fns_nn:
    build: ..
    environment:
      - REDIS_URL
      - RABBIT_URL
    depends_on:
      - redis
      - queue
      - api
    command: ["python", "-m", "capts.businesslogic.start_nn", "fns"]

  alco_nn:
    build: ..
    environment:
      - REDIS_URL
      - RABBIT_URL
    depends_on:
      - redis
      - queue
      - api
    command: [ "python", "-m", "capts.businesslogic.start_nn", "alcolicenziat" ]