version: "2.4"

services:
  redis:
    image: "redis:alpine"
    ports:
      - 9999:6379
  api:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL
    command: 'uvicorn capts.app.main:app --host 0.0.0.0 --port 8080'
