version: "2.4"

services:
  redis:
    image: redis:alpine
    restart: on-failure

  queue:
    image: rabbitmq:3-management-alpine
    restart: on-failure

  api:
    build: ..
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - redis
      - queue
    command: ["uvicorn", "capts.app.main:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: on-failure

  fns_nn:
    build: ..
    env_file:
      - .env
    depends_on:
      - redis
      - queue
      - api
    command: ["python", "-m", "capts.businesslogic.start_nn", "fns"]
    restart: on-failure

  alco_nn:
    build: ..
    env_file:
      - .env
    depends_on:
      - redis
      - queue
      - api
    command: ["python", "-m", "capts.businesslogic.start_nn", "alcolicenziat"]
    restart: on-failure
